### PR TITLE
Remove @types/vscode in devDependencies 

### PR DESCRIPTION
**Pull request by xueli-hu**

### CODE REVIEW

**Review by jianhua-git — COMMENTED** [review]
checked

**Review by wb0716 — COMMENTED** [review]
Good

**Review by xujiangang-git — COMMENTED** [review]
checked

**Review by keyuan0701 — COMMENTED** [review]
gd

**Review by gkl54333 — COMMENTED** [review]
gd

**Review by fjk0401 — APPROVED** [review]
Good for me

**Pull request merged**
