### PR TITLE
support wits disconnect feature

### PR DESCRIPTION
**Pull request by tianhao-srcn**

### CODE REVIEW

**Review by keyuan0701 — COMMENTED** [review]
good

**Review by chunhua-liu — APPROVED** [review]

**Review by chunhua-liu — APPROVED** [review]
good

**Comment by wb0716** [comment]
good

**Review by jianhua-git — COMMENTED** [review]
checked

**Review by gkl54333 — COMMENTED** [review]
good

**Review by yan11meng — COMMENTED** [review]
good

**Comment by xujiangang-git** [comment]
checked

**Review by fjk0401 — COMMENTED** [review]
Good for me

**Pull request merged**
