### PR TITLE
Update version 1.2.0

### PR DESCRIPTION
**Pull request by keyuan0701**

### CODE REVIEW

**Review by gkl54333 — COMMENTED** [review]
good

**Review by xueli-hu — COMMENTED** [review]
good

**Review by jianhua-git — COMMENTED** [review]
checked

**Review by fjk0401 — COMMENTED** [review]
Good for me

**Review by tianhao-srcn — COMMENTED** [review]
checked

**Review by chunhua-liu — APPROVED** [review]

**Pull request merged**
