### PR TITLE
refactor and separating webIDE-common-tizentv

### PR DESCRIPTION
**Pull request by keyuan0701**

### CODE REVIEW

**Comment by gkl54333** [comment]
go'd

**Review by fjk0401 — COMMENTED** [review]
Good for me

**Review by tianhao-srcn — COMMENTED** [review]
checked

**Review by jianhua-git — COMMENTED** [review]
checked

**Review by xueli-hu — COMMENTED** [review]
good

**Review by xueli-hu — COMMENTED** [review]
good

**Review by chunhua-liu — APPROVED** [review]

**Pull request merged**
