### PR TITLE
release version 1.1.0

### PR DESCRIPTION
**Pull request by tianhao-srcn**

### CODE REVIEW

**Review by jianhua-git — COMMENTED** [review]
checked

**Review by keyuan0701 — COMMENTED** [review]
good

**Review by chunhua-liu — DISMISSED** [review]

**Comment by xujiangang-git** [comment]
checked

**Review by xueli-hu — COMMENTED** [review]
looks good

**Comment by wb0716** [comment]
checked

**Comment by wb0716** [comment]
checked

**Review by gkl54333 — COMMENTED** [review]
gd

**Review by chunhua-liu — APPROVED** [review]

**Review by chunhua-liu — APPROVED** [review]

**Pull request merged**
