### PR TITLE
Update wits description

### PR DESCRIPTION
**Pull request by tianhao-srcn**
1. Update wits description
2. Update version number

### CODE REVIEW

**Review by xueli-hu — COMMENTED** [review]
looks good

**Review by jianhua-git — COMMENTED** [review]
checked

**Review by keyuan0701 — COMMENTED** [review]
good

**Review by fjk0401 — COMMENTED** [review]
Good for me

**Comment by yan11meng** [comment]
good

**Comment by wb0716** [comment]
looks good

**Review by chunhua-liu — APPROVED** [review]

**Review by chunhua-liu — APPROVED** [review]

**Review by yan11meng — COMMENTED** [review]
good

**Review by chunhua-liu — APPROVED** [review]
good

**Review by chunhua-liu — APPROVED** [review]
good

**Pull request merged**
