### PR TITLE
Integrating @tizentv/tools interface

### PR DESCRIPTION
**Pull request by keyuan0701**

### CODE REVIEW

**Comment by gkl5433** [comment]
gd

**Review by jianhua-git — COMMENTED** [review]
checked

**Review by fjk0401 — COMMENTED** [review]
Good for me

**Review by xujiangang-git — COMMENTED** [review]
checked

**Review by xueli-hu — COMMENTED** [review]
good

**Review by chunhua-liu — APPROVED** [review]

**Pull request merged**
